config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
root "tasks#index"

  resources :tasks do
    collection do
      post:confirm
    end
  end

  namespace :admin do 
    resources :users 
  end  
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :tasks, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, length: { minimum: 6 }
  paginates_per 3  
  before_destroy :admin_exist_check
  before_update :admin_update_exist
    
  def admin_exist_check
      if User.where(role: true).count <= 1 && self.role == true
        throw(:abort)
      end
  end

  def admin_update_exist
    if User.where(role: true).count == 1 && self.role == false
      throw(:abort)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create, :edit]
    before_action :admin_users
    
    def index
      @users = User.all.includes(:tasks).page(params[:page])
    end
    
    def new
       @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          flash[:notice] = 'User create succesfully'
          redirect_to admin_users_path
        else
          render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @tasks = @user.tasks.all
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
          redirect_to admin_user_path(@user.id), notice: "User edited !"
      else
          render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      if current_user.id == @user.id
        redirect_to admin_users_path, notice: "Can't delete current user !"
      elsif
        if @user.destroy
          redirect_to admin_users_path, notice: "User has been delete !"
        else
          redirect_to admin_users_path, notice: "Can't delete laste admin!"
        end
      end  
    end
    
    private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation, :role)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def admin_users
      unless current_user.role?
        redirect_to tasks_path, notice: "Can't access the administration page !"
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create, :edit]
    def new
      if logged_in?
        flash[:notice] = 'New registrations must be logged out of the app.'
        redirect_to tasks_path
      else
        @user = User.new
      end
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:notice] = 'You are logged in.'
          redirect_to tasks_path(@user.id)
        else
          render :new
        end
    end

    def show
        @user = User.find(params[:id])
        if @user.id != current_user.id
          redirect_to tasks_path, notice: "Can't access this page"
        end
    end

    def edit
      @user = User.find(params[:id])
      if @user.id != current_user.id
        redirect_to tasks_path, notice: "Can't access this page"
      end  
    end

    def update
        @user = User.find(params[:id])
      if @user.id == current_user.id 
          if @user.update(user_params)
              redirect_to user_path(@user.id), notice: "J'ai modifié l'utilisateur !"
          else
              render :edit
          end
      else
          redirect_to tasks_path, notice: "Impossible de modifier l'utilisateur !"
      end
    end
    
    private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin,@user], local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:'form-control' %>
  </div>

  <div class="form-group">
      <%= form.label :Admin %>
      <%= form.check_box :role, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to 'Back', admin_users_path, class: 'btn btn-light mb-3' %>
<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-4">
            <span> <b> Editing User </b> </span>
        </h3>

        <%= render 'form', user: @user %>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="card" >
  <div class="card-body">

    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span> <b> <a class="text-decoration-none bg-color-none" href="<%=admin_users_path%>"> Users </a> </b> </span>  
      <%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary text-light' %> 
    </h2>  
    
      <% @users.each do |user| %>
       <%= link_to admin_user_path(user), class: 'text-decoration-none text-primary' do %> 
        <div class="card project-card mb-4" >
          <div class="card-body">
            
            <h5 class='card-title'> 
              <b> 
                <%= user.name %> 
              </b> 
            </h5>
            <p> 
              <%= user.email %> 
            </p>
            <p>
              <%= user.role %>
            </p>
            <p>
              <%= user.tasks.count %> task
            </p>
            
          </div>
        </div>
      <% end %>
    <% end %> 
    
      <%= paginate @users %>
        
  </div>
</div>

app/views/admin/users/new.html.erb
<%= link_to 'Back', admin_users_path, class: 'btn btn-light mb-3' %>
<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-4">
            <span> 
              <b> 
                New User 
              </b> 
            </span>
        </h3>

        <%= render 'form', user: @user %>
    </div>
</div>

app/views/admin/users/show.html.erb
<%= link_to 'Back', admin_users_path, class: 'btn btn-light mb-3' %>
<div class="card" >
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between'>
      <span> <b> <%= @user.name %> </b> </span>  
      <div> 
        <%= link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-light' %>
        <%= link_to 'Destroy', admin_user_path(@user), method: :delete, class: 'btn btn-secondary text-light', data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

      <p>
        <strong>Name : </strong>
        <%= @user.name %>                 
      </p>

      <p>
        <strong>Email : </strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Admin : </strong>
        <%= @user.role %>
      </p>

      <p>
        <strong>User Tasks : </strong>
        <%= @user.tasks.count %>
      </p>

    
  </div>
</div>
<br>
<br>

<div class="card" >
  <div class="card-body">

    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span> <b> <a class="text-decoration-none bg-color-none" ><%= @user.name %> Tasks </a> </b> </span>  
      <div class="input-group-append"> 
        <%= link_to 'Sort by Deadline', tasks_path(sort_expired: "true"), class: 'btn btn-outline-primary ' %> 
        <%= link_to 'Sort by Priority', tasks_path(sort_priority: "true"), class: 'btn btn-outline-primary ml-5' %> 
      </div>
      
    </h2>

    
        
        <%= form_with url: tasks_path, method: :get, local: true do |form| %>

          <div class="input-group mb-4"> 
            <%= form.text_field :name, class:'form-control' %>
            <div class="input-group-append">  
              <%= form.submit 'Search', class: 'btn btn-outline-primary mr-2' %> 
              <strong> <%= form.label :status %> </strong>
              <%= form.select :number, Task.statuses.keys.to_a, { include_blank:'Please select'} %> 
            </div>
          </div>
        <% end %>    
    
      <% @tasks.each do |task| %>
      <%= link_to task, class: 'text-decoration-none text-primary' do %>
        <div class="card project-card mb-4" >
          <div class="card-body">
            
            <h5 class='card-title'> <b> <%= task.name %> </b> </h5>
            <span class="badge badge-<%=task.badge_color%> mb-2">
              <%= task.status %>
            </span>
            <p> <%= task.retail %> </p>
            <p>
              <%= task.dead_line.strftime("%Y-%m-%d") %>
            </p>
            <p>
               <%= task.priority %>
            </p>
            <p>
               <%= task.user.name %>
            </p>

          </div>
        </div>
      <% end %>
    <% end %> 
            
  </div>
</div>